version: '3'
services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    command: yarn start
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: yarn start
    environment:
      NODE_ENV: production
      SECRET_KEY: 'SECRET_KEY'
      PORT: 8080
    ports:
      - "8080:8080"


